#!/bin/bash

# This hook is called with the snake-cased name of the theme that has just been tmux set.
# To put it into use, remove .sample from the name.

# Example: Show the name of the theme that was just tmux set.
notify-send "New theme" "Your new theme is $1"
