#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

CACHE="$HOME/.cache/tmpimg"


filetype="$( file -Lb --mime-type "$file")"
if [[ "$filetype" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
fi


if [[ "$filetype" = application/pdf ]]; then
    pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "${CACHE}.jpg" < /dev/null > /dev/tty
    exit 1
fi


bat --theme=ansi --style='numbers,changes,grid,full,header,header-filename,header-filesize,snip' --terminal-width "$(($4-2))" -f "$1"

